apiVersion: v1
data:
  tls.crt: {{ .Values.tls.certBase64 | required ".Values.tls.certBase64 is required." }}
  tls.key: {{ .Values.tls.keyBase64 | required ".Values.tls.keyBase64 is required." }}
kind: Secret
metadata:
  name: pod-identity-webhook-tls
  namespace: irsa
type: Opaque
